# Generated by Django 4.2.2 on 2023-08-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamintojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=50, verbose_name='Pavadinimas')),
                ('gaminimo_pradzia', models.IntegerField(verbose_name='Pradejo-gaminti')),
                ('aprasymas', models.TextField(max_length=2000, verbose_name='about')),
            ],
        ),
    ]
