# Generated by Django 4.2.2 on 2023-08-28 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motociklai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelis', models.CharField(max_length=50, verbose_name='Modelis')),
                ('metai_pasirode', models.IntegerField(verbose_name='Gaminimo-pradzia')),
                ('aprasymas', models.TextField(max_length=2000, verbose_name='Aprasymas')),
                ('gamintojasFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='motociklai.gamintojas')),
            ],
        ),
    ]
