# Generated by Django 4.2.2 on 2023-09-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motociklai', '0002_modelis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likutis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Pavadinimas')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gamintojas',
            options={'ordering': ['pavadinimas'], 'verbose_name_plural': 'Gamintojas'},
        ),
        migrations.AlterModelOptions(
            name='modelis',
            options={'verbose_name_plural': 'Modelis'},
        ),
        migrations.AlterField(
            model_name='gamintojas',
            name='aprasymas',
            field=models.TextField(max_length=3000, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='modelis',
            name='aprasymas',
            field=models.TextField(max_length=3000, verbose_name='Aprasymas'),
        ),
        migrations.AddField(
            model_name='modelis',
            name='likutis',
            field=models.ManyToManyField(to='motociklai.likutis'),
        ),
    ]
