# Generated by Django 4.2.2 on 2023-09-06 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('motociklai', '0003_likutis_alter_gamintojas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likutis',
            options={'verbose_name_plural': 'Likutis'},
        ),
        migrations.RenameField(
            model_name='modelis',
            old_name='gamintojasFK',
            new_name='gamintojas',
        ),
        migrations.AlterField(
            model_name='likutis',
            name='name',
            field=models.CharField(help_text='sukurkite likucio info', max_length=20, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='modelis',
            name='likutis',
            field=models.ManyToManyField(help_text='Isrinkite likucio bukle', to='motociklai.likutis'),
        ),
        migrations.CreateModel(
            name='ModelisInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('planuojama_gauti', models.DateField(blank=True, null=True, verbose_name='Turesime pardavime')),
                ('status', models.CharField(blank=True, choices=[('t', 'Turime sandelyje'), ('a', 'Atkeliauja'), ('n', 'Neturime'), ('r', 'Rezervuota')], default='a', help_text='Moto statusas', max_length=1)),
                ('modelis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motociklai.modelis')),
            ],
            options={
                'ordering': ['planuojama_gauti'],
            },
        ),
    ]
