# Generated by Django 4.2.2 on 2023-09-06 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motociklai', '0004_alter_likutis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamintojas',
            options={'ordering': ['pavadinimas'], 'verbose_name': 'Gamintojas', 'verbose_name_plural': 'Gamintojai'},
        ),
        migrations.AlterModelOptions(
            name='likutis',
            options={'verbose_name': 'Likutis', 'verbose_name_plural': 'Likuciai'},
        ),
        migrations.AlterModelOptions(
            name='modelis',
            options={'verbose_name': 'Modelis', 'verbose_name_plural': 'Modeliai'},
        ),
        migrations.AlterField(
            model_name='modelis',
            name='gamintojas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeliai', to='motociklai.gamintojas'),
        ),
    ]
