# Generated by Django 4.2.2 on 2023-09-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motociklai', '0005_alter_gamintojas_options_alter_likutis_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelis',
            name='aprasymas',
        ),
        migrations.AddField(
            model_name='modelis',
            name='modelis_aprasymas',
            field=models.TextField(max_length=3000, null=True, verbose_name='aprasymas'),
        ),
    ]
