# Generated by Django 4.2.2 on 2023-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motociklai', '0007_alter_modelisinstance_modelis'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelis',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Virselis'),
        ),
        migrations.AlterField(
            model_name='modelis',
            name='modelis_aprasymas',
            field=models.TextField(max_length=3000, null=True, verbose_name='Aprasymas'),
        ),
    ]
