# Generated by Django 4.2.2 on 2023-09-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motociklai', '0008_modelis_cover_alter_modelis_modelis_aprasymas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelis',
            name='cover',
        ),
    ]
