# Generated by Django 4.2.2 on 2023-09-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motociklai', '0009_remove_modelis_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelis',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Virselis'),
        ),
    ]
