# Generated by Django 4.2.2 on 2023-09-09 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motociklai', '0010_modelis_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelisinstance',
            name='klientas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelis',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Virselis'),
        ),
    ]
